# Create Shift Record
'https://dev.firstchoicenurses.com/api/v1/mobile/obj/facility/shift/create'
method = 'POST'
headers = REQUIRED_HEADERS_FOR_TOKEN_AUTH
post_fields = {
	    "department": <type: string. Required>,
	    "date": <type: integer (timestamp). Required>,
	    "classification": <type: string. Required>,
	    "start_datetime": <type: integer (timestamp). Required>,
	    "stop_datetime": <type: integer (timestamp). Required>,,
	    "hospital": <type: integer (primary_key). Required>,
	    "shift": <type: string (example: '8A-5P'). Optional>,
	    "comments": <type: string. Optional>,
	    "client": <type: string. Optional>
	}

returns = {
    "id": 199916,
    "comments": null,
    "timestamp": 1644349813,
    "submitted_by_nurse": false,
    "submitted_by_nurse_timestamp": 1644349813,
    "is_draft": false,
    "is_rejected": false,
    "cancelled": false,
    "certified": false,
    "certified_on": null,
    "start_datetime": 1644253229,
    "stop_datetime": 1644347158,
    "clock_in_at": null,
    "clock_in_location": "",
    "clock_in_latitude": null,
    "clock_in_longitude": null,
    "clock_out_at": null,
    "clock_out_location": "",
    "clock_out_latitude": null,
    "clock_out_longitude": null,
    "daylight_saving_time": "",
    "duration": "1 02:05:29",
    "regular_duration": null,
    "break_duration": null,
    "overtime_duration": null,
    "holiday_duration": null,
    "import_lock": false,
    "client": "",
    "department": "TEST DEPT",
    "date": 1644210000,
    "classification": "TEST Classification",
    "ordered_by": "",
    "received": null,
    "received_by": "nurse111104531",
    "assigned": null,
    "assigned_by": "",
    "first_assigned": null,
    "confirmed": null,
    "confirmed_by": "",
    "confirmed_to": "",
    "shift": "",
    "start_time": null,
    "stop_time": null,
    "regular_hours": null,
    "break_hours": null,
    "overtime_hours": null,
    "holiday_hours": null,
    "travel": null,
    "check_date": null,
    "check_number": null,
    "check_amount": null,
    "invoice_number": null,
    "invoice_date": null,
    "invoice_amount": null,
    "ok_to_bill": false,
    "ok_overtime": true,
    "exported": false,
    "site": null,
    "paychex_id": null,
    "worker": "",
    "keyfield": "eb2af34e-8afb-4c34-ae2d-3c64cc329518",
    "hospital": {
        "id": 81,
        "comments": "",
        "timestamp": 1642871603,
        "shortcode": "ARCONI",
        "name": "Arconic - Hampton",
        "attention": null,
        "address": "1 Howmet  Drive",
        "address2": null,
        "city": "Hampton",
        "st": "VA",
        "zipcode": "23661",
        "contact": "Michael Jenkins and Forres",
        "phone": "+17578384680",
        "phone1": "",
        "phone2": "",
        "phone3": "",
        "vfemail": "Michael.Jenkins@arconic.comForrest.Collins@arconic.com",
        "vfcomments": "",
        "show_aging": false,
        "facility_type": "Facility",
        "account_representative": "",
        "invoice_method": "",
        "early_pay_discount_rate": "0.0000",
        "early_pay_due": 0,
        "invoice_due": 0,
        "invoice_late_rate": "0.0000",
        "invoice_late_fee": "0.00",
        "factoring_agent": "",
        "auto_add_travel": false,
        "round_invoice_hours": false,
        "site": "NEWPO",
        "covid_vaccine": false,
        "notes": "",
        "covid_exemption": false,
        "notes_for_covid_exemption": "",
        "admins": [
            83,
            23
        ]
    },
    "profile": null,
    "nurse": {
        "id": 3971,
        "fname": "",
        "lname": "",
        "email": null,
        "phone": "+17575813458",
        "dob": null,
        "photo": null
    },
    "accepted_nurse": null,
    "certified_by": null,
    "received_by_user": 92,
    "assigned_by_user": null,
    "first_assigned_by_user": null,
    "booked": [],
    "submitted_nurse_shift_files": [],
    "status": "unassigned"
}
