# Get all future shifts for special facility
'https://dev.firstchoicenurses.com/api/v1/mobile/obj/facility/<int:facility_id>/get-future-shifts'
method = 'GET'
headers = REQUIRED_HEADERS_FOR_TOKEN_AUTH
get_fields = 'special get fields are not needed'

returns = [  # array with objects
	    {
		"id": 199898,
		"comments": "TEST",
		"timestamp": "2022-01-18T15:56:20.247043-05:00",
		"submitted_by_nurse": false,
		"submitted_by_nurse_timestamp": "2022-01-18T15:56:20.247065-05:00",
		"is_draft": false,
		"cancelled": false,
		"certified": false,
		"certified_on": null,
		"start_datetime": "2022-01-19T15:00:00-05:00",
		"stop_datetime": "2022-01-19T23:00:00-05:00",
		"clock_in_at": null,
		"clock_in_location": "",
		"clock_in_latitude": null,
		"clock_in_longitude": null,
		"clock_out_at": null,
		"clock_out_location": "",
		"clock_out_latitude": null,
		"clock_out_longitude": null,
		"daylight_saving_time": "undefined",
		"duration": "08:00:00",
		"regular_duration": null,
		"break_duration": null,
		"overtime_duration": null,
		"holiday_duration": null,
		"import_lock": false,
		"client": "NANSPT",
		"department": "ORIENT",
		"date": "2022-01-19",
		"classification": "LPN",
		"ordered_by": "Gennette - Staff Developm",
		"received": "2022-01-18T15:56:20.216494-05:00",
		"received_by": "admin",
		"assigned": null,
		"assigned_by": "",
		"first_assigned": null,
		"confirmed": null,
		"confirmed_by": "",
		"confirmed_to": "",
		"shift": "03PM-11PM",
		"start_time": 1500,
		"stop_time": 2300,
		"regular_hours": null,
		"break_hours": null,
		"overtime_hours": null,
		"holiday_hours": null,
		"travel": null,
		"check_date": null,
		"check_number": null,
		"check_amount": null,
		"invoice_number": null,
		"invoice_date": null,
		"invoice_amount": null,
		"ok_to_bill": false,
		"ok_overtime": true,
		"exported": false,
		"site": "NEWPO",
		"paychex_id": null,
		"worker": "",
		"keyfield": "0c04fd01-52fa-4ff5-b9cf-a1a37b1f6c21",
		"hospital": 14,
		"profile": null,
		"nurse": 3971,
		"accepted_nurse": null,
		"certified_by": null,
		"received_by_user": 23,
		"assigned_by_user": null,
		"first_assigned_by_user": null,
		"booked": []
	    },
	    ...
    ]
